### PR TITLE
add java BatchSynthesis

### PR DESCRIPTION
**Pull request by tomj2ee**
## Purpose

* ...

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by tomj2ee** [comment]
[Feature]

**Comment by tomj2ee** [comment]
@microsoft-github-policy-service agree

**Comment by yulin-li** [comment]
@tomj2ee thanks for contribute this! we are reviewing

**Review by yulin-li — APPROVED** [review]

**Pull request merged**
