### PR TITLE
Removing the link to azure docs

### PR DESCRIPTION
**Pull request by RohitMungi-MSFT**
Removing the link to azure docs as detailed steps are actually available in this readme file to run this solution

## Purpose

Removes unwanted links to azure docs where steps are not available to run this solution. Customer raised an issue with the link in this docs [issue](https://github.com/MicrosoftDocs/azure-docs/issues/49628).

## Pull Request Type
What kind of change does this Pull Request introduce?
Removes a hyperlink to azure docs where detailed steps are not available

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by RohitMungi-MSFT** [comment]
Closes: MicrosoftDocs/azure-docs/issues/49628

**Comment by RohitMungi-MSFT** [comment]
#sign-off

**Comment by IEvangelist** [comment]
#reassign: @BrianMouncer

**Comment by RohitMungi-MSFT** [comment]
@IEvangelist Could you please re-review the PR since the folder structure has changed I have updated the changes in all README files to remove reference to the docs repo.

**Comment by IEvangelist** [comment]
> @IEvangelist Could you please re-review the PR since the folder structure has changed I have updated the changes in all README files to remove reference to the docs repo.

I'm no longer on this Azure docs team. I joined the .NET docs, I'll do this last review though.

**Review by dargilco — APPROVED** [review]

**Pull request merged**
