### PR TITLE
update fluency score calculation in pronunciation assessment score 

### PR DESCRIPTION
**Pull request by yulin-li**
…mple

## Purpose

* ...

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by yinhew** [comment]
sign off

**Review by yinhew — APPROVED** [review]
looks good

**Comment by yulin-li** [comment]
Hi @BrianMouncer, Yinhe reviewed this PR but he doesn't have write permission, could you also help me to review this?

**Review by BrianMouncer — APPROVED** [review]
:shipit:

**Pull request merged**
