### PR TITLE
Add a check to see if Conv PII is enabled

### PR DESCRIPTION
**Pull request by bidisha-c**
## Purpose

* ...

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by HenryvanderVegte — APPROVED** [review]

**Review by HenryvanderVegte — APPROVED** [review]

**Comment by BrianMouncer** [comment]
Close and re-open to see if it triggers a PR build.

**Comment by BrianMouncer** [comment]
Close and re-open to see if it triggers a PR build.

**Comment by HenryvanderVegte** [comment]
@bidisha-c before merging, please remove the profile.arm.json files and increment the ingestion client pkg version(s)

**Review by BrianMouncer — APPROVED** [review]
/AzurePipelines run

**Pull request closed without merging**
