### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by rsarosh**
Small notes added which may throw off a noob. These small notes may save many hours of frustration.

## Purpose

* ...

## Pull Request Type
Added  few small issues clarification in the readme.md 

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by dargilco** [comment]
@rsarosh thank you for the great feedback and the suggested edits to the readme. I appreciate you spending time creating this PR making sure other developers benefit from your learnings. 

Some of your notes should probably be mentioned directly in the "Run the sample code" section, instead of in a new Notes section at the end. For example, your clarification on subscription key and region, should be placed in "1. Your subscription key and region.".  You should mention that "East US" is just an example (at the moment it sounds like that's the only value that is supported). And point to this link which lists all the supported Azure regions for REST APIs: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#rest-apis

If you want to do another round of edits to this PR based on my feedback, feel free to do so. Otherwise, me or someone else from the Speech SDK team will do some edits and complete the PR.

Thanks!

Darren

**Comment by rsarosh** [comment]
sure, will send another PR.

**Comment by rsarosh** [comment]
Created a new PR, addressing @dargilco comments

**Comment by chlandsi** [comment]
Hi @rsarosh, thank you for your contribution, it is much appreciated. I'll make some edits and add them to the sample.

**Review by dargilco — APPROVED** [review]

**Comment by dargilco** [comment]
@rsarosh I merged your change. Thank you very much! Feel free to suggest other changes when you see the need. 
Darren

**Pull request merged**
