### PR TITLE
Fix SpeechRecognitionLanguage has not been properly set in captioning scenario

### PR DESCRIPTION
**Pull request by kaotoby**
## Purpose

* Fix SpeechRecognitionLanguage has not been properly set in captioning scenario.

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by BrianMouncer — APPROVED** [review]

**Comment by BrianMouncer** [comment]
trying to kick PR build to start.

**Review by BrianMouncer — APPROVED** [review]

**Review by BrianMouncer — APPROVED** [review]
thank you.

**Comment by kaotoby** [comment]
fixed in #1724

**Pull request closed without merging**
