### PR TITLE
Update the biology testing dataset for Custom Speech en-us locale

### PR DESCRIPTION
**Pull request by RichardSunMS**
Update the biology testing dataset for Custom Speech en-us locale

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: Sample data.
```

### CODE REVIEW

**Review by yulin-li — APPROVED** [review]

**Comment by RichardSunMS** [comment]
Hi Mark/Brian, can you help check why this check is always pending? Azure-Samples.cognitive-services-speech-sdk-samples

**Comment by RichardSunMS** [comment]
> Hi Mark/Brian, can you help check why this check is always pending? Azure-Samples.cognitive-services-speech-sdk-samples

@mahilleb-msft , @BrianMouncer , can you help check why it always keep pending?

**Pull request merged**
