### PR TITLE
edit pass

### PR DESCRIPTION
**Pull request by v-demjoh**
## Purpose
Edit pass

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by v-demjoh** [comment]
#sign-off

**Comment by v-demjoh** [comment]
@BrianMouncer  merge this to avoid collisions.

**Comment by BrianMouncer** [comment]
The Batch API Sample are not a part of the Client SDK.  They should be kept separated under https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch

**Comment by v-demjoh** [comment]
@BrianMouncer  Perhaps this writing should be relocated, but a worse draft is in master at samples/ingestion/ingestion-client/Setup/guide.md today, and this PR should merge with it today, to avoid collisions that are being written today.

**Comment by v-demjoh** [comment]
Then @PanosPeriorellis can relocate the tree, if I'm following correctly.

**Comment by PanosPeriorellis** [comment]
> Then @PanosPeriorellis can relocate the tree, if I'm following correctly.

Guys, the folder structure is correct. the reference to batch is about the tool operation. NOT The API samples that are in a separate folder. Please merge.

**Pull request merged**
