### PR TITLE
Remove sentence with broken link in Java Script translation README

### PR DESCRIPTION
**Pull request by dargilco**
Looks like a bad merge that kept an old line with a broken link. There is already a sentence there with a working link to the translation page. I see similar sentences in the other JS pages.

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by yulin-li** [comment]
seems the link is changed to https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-translation?tabs=import%2Cwindowsinstall&pivots=programming-language-javascript

**Comment by dargilco** [comment]
@yulin-li The technical writer removed all direct links to the quick-start at the relevant language, and replaced them with a link to the main topic page. This is because the README in the samples already includes the step-by-step instructions of how to build and run the sample. So it's best to link to the main topic page (speech translation page in this case) instead of the java script page for speech translation. He did this change a while back for many samples. In this particular sample however the old link was left.. I'm sure it's due to bad merge resolve. So I'm removing the old link and keeping the new link that the tech writer added. If that's okay with you, please sign-off on the change as is. Thanks!

**Comment by yulin-li** [comment]
@dargilco sorry I didn't know the background. signed-off

**Review by yulin-li — APPROVED** [review]
:shipit:

**Pull request merged**
