### PR TITLE
Updating sample code to use latest API versions

### PR DESCRIPTION
**Pull request by ut-karsh**
## Purpose

* Updated Speech REST API version to 3.1 and ConvesationAnalysis API version to 2022-10-01-preview.

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x ] Other... Please describe: Updating API versions, no functional changes.
```

### CODE REVIEW

**Comment by ut-karsh** [comment]
@trrwilson for review.

**Review by trrwilson — APPROVED** [review]

**Comment by trrwilson** [comment]
Looks great! Let's see if we can get the build to run...

**Review by BrianMouncer — APPROVED** [review]
/AzurePipelines run

**Pull request merged**
