### PR TITLE
Added sample data for custom speech.

### PR DESCRIPTION
**Pull request by RichardSunMS**
Added sample data for custom speech for tier-1 locales.

### CODE REVIEW

**Comment by mahilleb-msft** [comment]
> Content like data, models, tests, and endpoints are organized into Projects in the Custom Speech portal. Each project is specific to a domain and country/language. For example, you may create a project for call centers that use English in the United States.To create your first project, select the Speech-to-text/Custom speech, then click New Project. Follow the instructions provided by the wizard to create your project. After you've created a project, you should see four tabs: Data, Testing, Training, and Deployment. Use the links provided in Next steps to learn how to use each tab.

missing space before `To`

---
Refers to: sampledata/customspeech/en-US/training/related-text.txt:1 in e595109. [](commit_id = e595109b1c3d69066091e4b433dda182b0afbf23, deletion_comment = False)

**Comment by mahilleb-msft** [comment]
please add `*.zip binary` as a last line of the top-level `.gitattributes` files

**Comment by RichardSunMS** [comment]
> > Content like data, models, tests, and endpoints are organized into Projects in the Custom Speech portal. Each project is specific to a domain and country/language. For example, you may create a project for call centers that use English in the United States.To create your first project, select the Speech-to-text/Custom speech, then click New Project. Follow the instructions provided by the wizard to create your project. After you've created a project, you should see four tabs: Data, Testing, Training, and Deployment. Use the links provided in Next steps to learn how to use each tab.
> 
> missing space before `To`
> 
> Refers to: sampledata/customspeech/en-US/training/related-text.txt:1 in [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23). [](commit_id = [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23), deletion_comment = False)

**Comment by RichardSunMS** [comment]
> please add `*.zip binary` as a last line of the top-level `.gitattributes` files

Updated.

**Comment by RichardSunMS** [comment]
> > Content like data, models, tests, and endpoints are organized into Projects in the Custom Speech portal. Each project is specific to a domain and country/language. For example, you may create a project for call centers that use English in the United States.To create your first project, select the Speech-to-text/Custom speech, then click New Project. Follow the instructions provided by the wizard to create your project. After you've created a project, you should see four tabs: Data, Testing, Training, and Deployment. Use the links provided in Next steps to learn how to use each tab.
> 
> missing space before `To`
> 
> Refers to: sampledata/customspeech/en-US/training/related-text.txt:1 in [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23). [](commit_id = [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23), deletion_comment = False)

Fixed.

**Comment by mahilleb-msft** [comment]
> El contenido, como datos, modelos, pruebas y puntos de conexión, se organiza en proyectos en el portal de Custom Speech. Cada proyecto es específico de un dominio y un país o idioma. Por ejemplo, puede crear un proyecto para centros de llamadas que usan el inglés en Estados Unidos.Para crear su primer proyecto, seleccione Speech-to-text/Custom speech (Conversión de voz a texto/Conversión de voz personalizada) y, a continuación, haga clic en New project (Nuevo proyecto). Siga las instrucciones del asistente para crear el proyecto. Después de crear el proyecto, verá cuatro pestañas: Datos, Pruebas, Entrenamiento e Implementación. Use los vínculos incluidos en Pasos siguientes para aprender a usar cada pestaña.

space missing before `Para`

---
Refers to: sampledata/customspeech/es-ES/training/related-text.txt:1 in e595109. [](commit_id = e595109b1c3d69066091e4b433dda182b0afbf23, deletion_comment = False)

**Comment by RichardSunMS** [comment]
> > El contenido, como datos, modelos, pruebas y puntos de conexión, se organiza en proyectos en el portal de Custom Speech. Cada proyecto es específico de un dominio y un país o idioma. Por ejemplo, puede crear un proyecto para centros de llamadas que usan el inglés en Estados Unidos.Para crear su primer proyecto, seleccione Speech-to-text/Custom speech (Conversión de voz a texto/Conversión de voz personalizada) y, a continuación, haga clic en New project (Nuevo proyecto). Siga las instrucciones del asistente para crear el proyecto. Después de crear el proyecto, verá cuatro pestañas: Datos, Pruebas, Entrenamiento e Implementación. Use los vínculos incluidos en Pasos siguientes para aprender a usar cada pestaña.
> 
> space missing before `Para`
> 
> Refers to: sampledata/customspeech/es-ES/training/related-text.txt:1 in [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23). [](commit_id = [e595109](https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/e595109b1c3d69066091e4b433dda182b0afbf23), deletion_comment = False)

Fixed all these places without the space after . 
Thanks.

**Comment by mahilleb-msft** [comment]
> El contenido, como datos, modelos, pruebas y puntos de conexión, se organiza en proyectos en el portal de Custom Speech. Cada proyecto es específico de un dominio y un país o idioma. Por ejemplo, puede crear un proyecto para centros de llamadas que usan el inglés en Estados Unidos.Para crear su primer proyecto, seleccione Speech-to-text/Custom speech (Conversión de voz a texto/Conversión de voz personalizada) y, a continuación, haga clic en New project (Nuevo proyecto). Siga las instrucciones del asistente para crear el proyecto. Después de crear el proyecto, verá cuatro pestañas: Datos, Pruebas, Entrenamiento e Implementación. Use los vínculos incluidos en Pasos siguientes para aprender a usar cada pestaña.

(also in other files `git grep -P "\.\S" "sampledata/*txt"`)

---
In reply to: [532555477](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/378#issuecomment-532555477) [](ancestors = 532555477)

---
Refers to: sampledata/customspeech/es-ES/training/related-text.txt:1 in e595109. [](commit_id = e595109b1c3d69066091e4b433dda182b0afbf23, deletion_comment = False)

**Comment by mahilleb-msft** [comment]
> El contenido, como datos, modelos, pruebas y puntos de conexión, se organiza en proyectos en el portal de Custom Speech. Cada proyecto es específico de un dominio y un país o idioma. Por ejemplo, puede crear un proyecto para centros de llamadas que usan el inglés en Estados Unidos.Para crear su primer proyecto, seleccione Speech-to-text/Custom speech (Conversión de voz a texto/Conversión de voz personalizada) y, a continuación, haga clic en New project (Nuevo proyecto). Siga las instrucciones del asistente para crear el proyecto. Después de crear el proyecto, verá cuatro pestañas: Datos, Pruebas, Entrenamiento e Implementación. Use los vínculos incluidos en Pasos siguientes para aprender a usar cada pestaña.

some of the text files included in the .zip's also have this problem -- example:
audio1.wav Content like data, models, tests, and endpoints are organized into Projects in the Custom Speech portal. Each project is specific to a domain and country/language. For example, you may create a project for call centers that use English in the United States.To create your first project, select the Speech-to-text/Custom speech, then click New Project. Follow the instructions provided by the wizard to create your project. After you've created a project, you should see four tabs: Data, Testing, Training, and Deployment. Use the links provided in Next steps to learn how to use each tab.


---
In reply to: [532557881](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/378#issuecomment-532557881) [](ancestors = 532557881,532555477)

---
Refers to: sampledata/customspeech/es-ES/training/related-text.txt:1 in e595109. [](commit_id = e595109b1c3d69066091e4b433dda182b0afbf23, deletion_comment = False)

**Comment by mahilleb-msft** [comment]
> El contenido, como datos, modelos, pruebas y puntos de conexión, se organiza en proyectos en el portal de Custom Speech. Cada proyecto es específico de un dominio y un país o idioma. Por ejemplo, puede crear un proyecto para centros de llamadas que usan el inglés en Estados Unidos.Para crear su primer proyecto, seleccione Speech-to-text/Custom speech (Conversión de voz a texto/Conversión de voz personalizada) y, a continuación, haga clic en New project (Nuevo proyecto). Siga las instrucciones del asistente para crear el proyecto. Después de crear el proyecto, verá cuatro pestañas: Datos, Pruebas, Entrenamiento e Implementación. Use los vínculos incluidos en Pasos siguientes para aprender a usar cada pestaña.

also `git grep ' : '` [remove space before colon]

---
In reply to: [532560317](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/378#issuecomment-532560317) [](ancestors = 532560317,532557881,532555477)

---
Refers to: sampledata/customspeech/es-ES/training/related-text.txt:1 in e595109. [](commit_id = e595109b1c3d69066091e4b433dda182b0afbf23, deletion_comment = False)

**Comment by mahilleb-msft** [comment]
please add a README.md (in sampledata/customspeech/ maybe) describing what this is all about and what the struucture of things are (locale, files etc.). Check other README for comparison. Put a link back to the azure-docs custom speech documentation.

Also add a new section (`## Sample data for Custom Speech` ?) into the top-level README.md, maybe before `## Resources` and link to the data you added.

**Comment by erhopf** [comment]
@RichardSunMS - Which files do you need my review on?

**Comment by RichardSunMS** [comment]
> please add a README.md (in sampledata/customspeech/ maybe) describing what this is all about and what the struucture of things are (locale, files etc.). Check other README for comparison. Put a link back to the azure-docs custom speech documentation.
> 
> Also add a new section (`## Sample data for Custom Speech` ?) into the top-level README.md, maybe before `## Resources` and link to the data you added.

added one, please take a look and see whether looks good.

**Comment by RichardSunMS** [comment]
> @RichardSunMS - Which files do you need my review on?

It's fine if you don't have comment. :)

**Comment by erhopf** [comment]
@RichardSunMS - Is this PR still valid?

**Comment by RichardSunMS** [comment]
> @RichardSunMS - Is this PR still valid?

Yes.

**Comment by RichardSunMS** [comment]
> Talked with Richard in person and approve as delegated.

**Pull request merged**
